# Generated by Django 3.1.7 on 2021-10-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_auto_20211001_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='store_id',
        ),
        migrations.AddField(
            model_name='image',
            name='user_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
