# Generated by Django 3.1.7 on 2021-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='store_user',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
