# Generated by Django 3.1.7 on 2021-10-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_notification_store_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='store_id',
            new_name='store_user',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='shop',
            name='store_user',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
