# Generated by Django 3.1.7 on 2021-10-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0009_auto_20211004_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='store_user',
            new_name='reciver',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
