# Generated by Django 3.1.7 on 2021-10-09 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0012_image_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('reciver', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image1', models.ImageField(default='default.jpg', upload_to='images')),
                ('image2', models.ImageField(default='default.jpg', upload_to='images')),
                ('image3', models.ImageField(default='default.jpg', upload_to='images')),
                ('image4', models.ImageField(default='default.jpg', upload_to='images')),
                ('image5', models.ImageField(default='default.jpg', upload_to='images')),
                ('desc', models.TextField()),
            ],
        ),
    ]
