# Generated by Django 3.1.7 on 2021-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0013_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
