# Generated by Django 3.1.7 on 2021-10-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0016_auto_20211013_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='responed_status',
            field=models.CharField(default='not_responded', max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
