# Generated by Django 3.1.7 on 2021-10-23 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0018_placedorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorders',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
