# Generated by Django 3.1.7 on 2021-10-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0020_placedorders_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
