# Generated by Django 3.1.7 on 2021-10-29 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0021_user_type_is_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=200)),
                ('respondstatus', models.CharField(max_length=200)),
                ('customername', models.CharField(max_length=200)),
                ('customeraddress', models.CharField(max_length=500)),
                ('customermobile', models.CharField(max_length=200)),
                ('storename', models.CharField(max_length=200)),
                ('storeaddress', models.CharField(max_length=500)),
                ('storemobile', models.CharField(max_length=200)),
                ('storecity', models.CharField(max_length=200)),
                ('storedistance', models.CharField(max_length=2000)),
                ('delivername', models.CharField(max_length=200)),
                ('deliverusername', models.CharField(max_length=200)),
                ('delivermobile', models.CharField(max_length=200)),
                ('pricestatus', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('itemphoto', models.ImageField(default='default.jpg', upload_to='images')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
