# Generated by Django 3.1.7 on 2021-10-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0022_getdelivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetDelivery',
            new_name='GetDeliveries',
        ),
    ]
