# Generated by Django 3.1.7 on 2021-10-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0023_auto_20211029_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='mobile',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
