# Generated by Django 3.1.7 on 2021-10-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0025_auto_20211030_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getdeliveries',
            old_name='storename',
            new_name='store_name',
        ),
        migrations.AddField(
            model_name='getdeliveries',
            name='storeuser',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
