# Generated by Django 3.1.7 on 2021-11-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0028_auto_20211101_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorders',
            name='inbox_items',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
