# Generated by Django 3.1.7 on 2021-11-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0030_auto_20211103_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorders',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
    ]
