# Generated by Django 3.1.7 on 2021-11-04 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0031_placedorders_order_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=500)),
                ('c_username', models.CharField(max_length=200)),
                ('s_username', models.CharField(max_length=200)),
                ('images_id', models.CharField(max_length=300)),
                ('items', models.CharField(max_length=2000)),
                ('inbox_items', models.CharField(max_length=5000)),
                ('city', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=2000)),
                ('pincode', models.CharField(max_length=2000)),
                ('phone', models.CharField(max_length=2000)),
                ('price', models.CharField(max_length=2000)),
                ('store_notification_1', models.TextField(verbose_name='')),
                ('order_accept_status', models.CharField(default='not_responded', max_length=200)),
                ('user_notification_1', models.TextField(verbose_name='')),
                ('payment_status', models.CharField(default='not_responded', max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
