# Generated by Django 3.1.7 on 2021-11-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0032_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='d_response_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='d_username',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='deliver_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='on_way_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_picked_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='reached_location_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='store_status',
            field=models.BooleanField(default=False),
        ),
    ]
