# Generated by Django 3.1.7 on 2021-11-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0034_orders_dist_d_to_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='store_status',
        ),
    ]
