# Generated by Django 3.1.7 on 2021-11-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0035_remove_orders_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_reached_store',
            field=models.BooleanField(default=False),
        ),
    ]
