# Generated by Django 3.1.7 on 2021-11-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0036_orders_is_reached_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='itemphoto',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
