# Generated by Django 3.1.7 on 2021-11-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0037_orders_itemphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='billimage_store',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
