# Generated by Django 3.1.7 on 2021-11-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0038_orders_billimage_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='store_amount',
            field=models.CharField(default='', max_length=200),
        ),
    ]
