# Generated by Django 3.1.7 on 2021-11-09 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0040_auto_20211109_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='images')),
                ('order_id', models.CharField(max_length=200)),
            ],
        ),
    ]
