# Generated by Django 3.1.7 on 2021-11-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0041_storebill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_bill_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
