# Generated by Django 3.1.7 on 2021-11-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0042_orders_is_bill_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rejection_reason',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
