# Generated by Django 3.1.7 on 2021-11-09 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0043_orders_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='images')),
                ('order_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='parsel_img_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
