# Generated by Django 3.1.7 on 2021-11-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0044_auto_20211109_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_parsel_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
