# Generated by Django 3.1.7 on 2021-11-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0045_orders_is_parsel_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
