# Generated by Django 3.1.7 on 2021-11-11 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0047_orders_order_accept_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_accept_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
