# Generated by Django 3.1.7 on 2021-11-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0048_auto_20211111_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_accept_time',
            field=models.CharField(max_length=200),
        ),
    ]
