# Generated by Django 3.1.7 on 2021-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0049_auto_20211112_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.BooleanField(default=False)),
                ('second', models.BooleanField(default=False)),
                ('third', models.BooleanField(default=False)),
                ('fourth', models.BooleanField(default=False)),
            ],
        ),
    ]
