# Generated by Django 3.1.7 on 2021-11-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0050_notificationreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationreminder',
            name='order_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
