# Generated by Django 3.1.7 on 2021-11-15 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0052_auto_20211114_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('lat', models.CharField(max_length=500)),
                ('lon', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('selfie', models.ImageField(upload_to='images')),
                ('adhar', models.ImageField(upload_to='images')),
            ],
        ),
    ]
