# Generated by Django 3.1.7 on 2021-11-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0053_deliverypartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pay_phone',
            field=models.CharField(blank='', default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='storeadhar',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='shop',
            name='storelicence',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='shop',
            name='storepan',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='shop',
            name='storephoto',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
