# Generated by Django 3.1.7 on 2021-11-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0054_auto_20211115_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lon',
            field=models.FloatField(),
        ),
    ]
