# Generated by Django 3.1.7 on 2021-11-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0056_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_otp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
