# Generated by Django 3.1.7 on 2021-11-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0058_orders_filled_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
