# Generated by Django 3.1.7 on 2021-12-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0059_orders_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_timeup',
            field=models.BooleanField(default=False),
        ),
    ]
