# Generated by Django 3.1.7 on 2021-12-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0060_orders_is_timeup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='d_response_status',
            new_name='order_picked',
        ),
    ]
