# Generated by Django 3.1.7 on 2021-12-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0061_auto_20211206_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='flat_no',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
