# Generated by Django 3.1.7 on 2021-12-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0062_orders_flat_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
